### ISSUE TITLE
High CPU usage after ipfilter load

### ISSUE THREAD

**Issue by Manuel5cc** [ngosang/docker-amule#51] opened 2024-08-04 08:44 UTC
I'm experiencing this issue since this morning. After the ipfilter file loads, there is some error apparently related with the zip compression and the container starts using huge amounts of cpu until it almost freezes the whole system.

I'm using this ipfilter file in the config:
http://upd.emule-security.org/ipfilter.zip

Here is the log, it runs normally until it loads ipfilter:

```
2024-08-04 09:03:13: Logging to stdout enabled
 2024-08-04 09:03:13: Initialising aMuleD 2.3.3 compiled with wxBase(GTK2) v3.2.4 and Boost 1.84
 2024-08-04 09:03:13: Checking if there is an instance already running...
 2024-08-04 09:03:13: No other instances are running.
 2024-08-04 09:03:13: Creditfile loaded, 143 clients are known
 2024-08-04 09:03:13: *** TCP socket (ECServer) listening on 0.0.0.0:4712
 2024-08-04 09:03:13: Created Server UDP-Socket at port 4665
 2024-08-04 09:03:13: ListenSocket: Ok.
 2024-08-04 09:03:13: Created Client UDP-Socket at port 4672
 2024-08-04 09:03:13: Loading server.met file: /home/amule/.aMule/server.met
!2024-08-04 09:03:13: 8 servers in server.met found
 2024-08-04 09:03:13: Loading temp files from /temp.
 2024-08-04 09:03:13: All PartFiles Loaded.
 2024-08-04 09:03:13: No part files found
 2024-08-04 09:03:13: Found 8 known shared files
!2024-08-04 09:03:13: web server running on pid 43
 2024-08-04 09:03:13: amuled: OnInit - starting timer
 2024-08-04 09:03:13: Asio thread 1 started
 2024-08-04 09:03:13: Asio thread 2 started
 2024-08-04 09:03:13: Asio thread 3 started
 2024-08-04 09:03:13: Asio thread 4 started
 2024-08-04 09:03:13: Loading IP filters 'ipfilter.dat' and 'ipfilter_static.dat'.
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
 2024-08-04 09:03:13: 09:03:13: Error: unsupported Zip compression method
```

**Comment by Takpeh** [comment] 2024-08-04 09:19
Good morning! The same thing happens to me since this morning. I've tried modifying the amule.config file, removing the address http://upd.emule-security.org/ipfilter.zip and disabling the automatic loading of filter.dat but the problem persists. Regards

**Comment by n1eko** [comment] 2024-08-04 09:31
Same here

**Comment by n1eko** [comment] 2024-08-04 09:33
I have the same problem

**Comment by ngosang** [comment] 2024-08-04 10:59
I having the same problem. It must be something in the last release of ipfilter => https://www.emule-security.org/
I fixed it by:
1. Stopping the container
2.  Setting `IPFilterAutoLoad=0` in amule.conf
3. Deleting all files starting with `ipfilter*`
4. Starting the container

If they publish a new release with this issue fixed I would like to re-enable this feature. Please, report back.

**Comment by Lordpedal** [comment] 2024-08-04 11:08
A global solution is launch a fix version with this `entrypoint.sh` change:

`IPFilterURL=http://upd.emule-security.org/ipfilter.zip`

To:

`IPFilterURL=http://emuling.gitlab.io/ipfilter.zip`

**Comment by Lordpedal** [comment] 2024-08-04 11:11
A better local solution is:

1.     Stopping the container
2.     Deleting all files starting with ipfilter*
3.     Change IPFilterURL to http://emuling.gitlab.io/ipfilter.zip in amule.conf
4.     Starting the container

**Comment by namelivia** [comment] 2024-08-04 15:34
Same problem here! I was puzzled since I had not changed the container and the sever stared going nuts last night. I fixed it switching to emuling's filter as suggested by @Lordpedal

**Comment by stochasticparrot42** [comment] 2024-08-05 08:40
Removing `ipfilter.dat` in config folder and relaunching the container seems to work. Probably the initial .zip file provided by emule-security folks had something wrong (but now seems to be fixed).

**Comment by xhente** [comment] 2024-08-05 17:50
Same problem here.

**Comment by toketin** [comment] 2024-08-05 19:27
I had the same issue yesterday, the cpu of the server machine was over 100%. I fixed deleting the `ipfilter*` files as reported by @Lordpedal

**Comment by Manuel5cc** [comment] 2024-08-06 13:25
I can confirm that using the emuling.gitlab.io sources fixes the issue for now.

**Comment by Marcosaurios** [comment] 2024-08-08 23:45
@Manuel5cc I'd advise to not close the issue until it's fixed properly in the codebase.

The solution @Lordpedal proposed seems very suitable for a PR, although I do not have the knowledge to assert his changes are for good (although it works perfectly fine, I'm not too experienced in Ed2k-related domain)

**Comment by ngosang** [comment] 2024-09-15 19:25
I'm going to close this issue since the problem was caused by https://www.emule-security.org/ and they already fix the problem long time ago.

For those who applied the solutions in this issue I recommend you to revert the changes and have this configuration:
* `IPFilterAutoLoad=1`
* `IPFilterURL=http://upd.emule-security.org/ipfilter.zip`

About emuling.gitlab.io:
* I don't know if they are trustworthy. upd.emule-security.org have been working for decades
* They don't update very often => https://gitlab.com/emuling/emuling.gitlab.io/-/commits/master?ref_type=heads
* It's good to have alternative just in case upd.emule-security.org stops working / updating.

**Closed by ngosang** 2024-09-15 19:25 UTC
Labels: bug, help wanted
